/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladorgo.view;

/**
 *
 * @author jardv
 */
public class CFrame extends javax.swing.JFrame {

    /**
     * Creates new form CFrame
     */
    public CFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemOpenFile = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        itemSaveAs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFile.setText("Archivo");

        itemOpenFile.setText("Abrir Archivo");
        itemOpenFile.setName("itemOpenFile"); // NOI18N
        menuFile.add(itemOpenFile);

        itemSave.setText("Guardar");
        itemSave.setName("itemSave"); // NOI18N
        menuFile.add(itemSave);

        itemSaveAs.setText("Guardar como");
        itemSaveAs.setName("itemSaveAs"); // NOI18N
        menuFile.add(itemSaveAs);

        menuBar.add(menuFile);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemOpenFile;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemSaveAs;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the itemOpenFile
     */
    public javax.swing.JMenuItem getItemOpenFile() {
        return itemOpenFile;
    }

    /**
     * @return the itemSave
     */
    public javax.swing.JMenuItem getItemSave() {
        return itemSave;
    }
    
    /**
     * @return the itemSaveAs
     */
    public javax.swing.JMenuItem getItemSaveAs() {
        return itemSaveAs;
    }
    
}
