/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladorgo.view;

import compiladorgo.util.TextLineNumber;
import javax.swing.JTextPane;

/**
 *
 * @author jardv
 */
public class CPanel extends javax.swing.JPanel {

    /**
     * Creates new form CPanel
     */
    public CPanel() {
        initComponents();
        TextLineNumber tlnCode = new TextLineNumber(codeTextArea);
        TextLineNumber tlnCodeOptimized = new TextLineNumber(codeOptimizedTextArea);
        this.codePanelArea.setRowHeaderView(tlnCode);
        this.codeOptimizedPanelArea.setRowHeaderView(tlnCodeOptimized);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        executePanel = new javax.swing.JPanel();
        typeCodePanel = new javax.swing.JPanel();
        lblCompilateCode = new javax.swing.JLabel();
        cbxCompilateCode = new javax.swing.JComboBox<>();
        bCompilate = new javax.swing.JButton();
        bOptimize = new javax.swing.JButton();
        codesPanel = new javax.swing.JPanel();
        codePanel = new javax.swing.JPanel();
        codePanelArea = new javax.swing.JScrollPane();
        codeTextArea = new javax.swing.JTextArea();
        lblFileSizeCodeNoOptimized = new javax.swing.JLabel();
        codeOptimizedPanel = new javax.swing.JPanel();
        codeOptimizedPanelArea = new javax.swing.JScrollPane();
        codeOptimizedTextArea = new javax.swing.JTextArea();
        lblFileSizeCodeOptimized = new javax.swing.JLabel();
        errorPanel = new javax.swing.JPanel();
        erroresPanel = new javax.swing.JPanel();
        panelLexical = new javax.swing.JPanel();
        errorPanelLexical = new javax.swing.JScrollPane();
        lexicalTextArea = new javax.swing.JTextArea();
        lexicalErrorNumPanel = new javax.swing.JPanel();
        labelLexicalErrorNum = new javax.swing.JLabel();
        panelSyntactic = new javax.swing.JPanel();
        errorPanelSyntactic = new javax.swing.JScrollPane();
        syntacticTextArea = new javax.swing.JTextArea();
        syntacticErrorNumPanel = new javax.swing.JPanel();
        labelSyntacticErrorNum = new javax.swing.JLabel();
        panelSemantic = new javax.swing.JPanel();
        errorPanelSemantic = new javax.swing.JScrollPane();
        semanticTextArea = new javax.swing.JTextArea();
        semanticErrorNumPanel = new javax.swing.JPanel();
        labelSemanticErrorNum = new javax.swing.JLabel();
        totalErrors = new javax.swing.JPanel();
        labelTotalErrors = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        setLayout(new java.awt.BorderLayout());

        lblCompilateCode.setText("Código a compilar:");
        typeCodePanel.add(lblCompilateCode);

        cbxCompilateCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No optimizado", "Optimizado" }));
        typeCodePanel.add(cbxCompilateCode);

        executePanel.add(typeCodePanel);

        bCompilate.setText("Compilar Código");
        bCompilate.setName("bCompilate"); // NOI18N
        executePanel.add(bCompilate);

        bOptimize.setText("Optimizar Código");
        bOptimize.setName("bOptimize"); // NOI18N
        executePanel.add(bOptimize);

        add(executePanel, java.awt.BorderLayout.NORTH);

        codesPanel.setLayout(new java.awt.GridLayout(1, 2));

        codePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código no Optimizado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        codePanel.setLayout(new java.awt.BorderLayout());

        codeTextArea.setColumns(20);
        codeTextArea.setRows(5);
        codePanelArea.setViewportView(codeTextArea);

        codePanel.add(codePanelArea, java.awt.BorderLayout.CENTER);

        lblFileSizeCodeNoOptimized.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFileSizeCodeNoOptimized.setText("Tamaño de archivo:");
        codePanel.add(lblFileSizeCodeNoOptimized, java.awt.BorderLayout.SOUTH);

        codesPanel.add(codePanel);

        codeOptimizedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código Optimizado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        codeOptimizedPanel.setLayout(new java.awt.BorderLayout());

        codeOptimizedTextArea.setEditable(false);
        codeOptimizedTextArea.setColumns(20);
        codeOptimizedTextArea.setRows(5);
        codeOptimizedPanelArea.setViewportView(codeOptimizedTextArea);

        codeOptimizedPanel.add(codeOptimizedPanelArea, java.awt.BorderLayout.CENTER);

        lblFileSizeCodeOptimized.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFileSizeCodeOptimized.setText("Tamaño de archivo:");
        codeOptimizedPanel.add(lblFileSizeCodeOptimized, java.awt.BorderLayout.SOUTH);

        codesPanel.add(codeOptimizedPanel);

        add(codesPanel, java.awt.BorderLayout.CENTER);

        errorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Errores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        errorPanel.setLayout(new java.awt.BorderLayout());

        erroresPanel.setLayout(new java.awt.GridLayout(1, 3));

        panelLexical.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Léxicos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        panelLexical.setLayout(new java.awt.BorderLayout());

        lexicalTextArea.setColumns(20);
        lexicalTextArea.setRows(5);
        errorPanelLexical.setViewportView(lexicalTextArea);

        panelLexical.add(errorPanelLexical, java.awt.BorderLayout.CENTER);

        lexicalErrorNumPanel.setLayout(new java.awt.BorderLayout());

        labelLexicalErrorNum.setText("Número de Errores:");
        lexicalErrorNumPanel.add(labelLexicalErrorNum, java.awt.BorderLayout.PAGE_START);

        panelLexical.add(lexicalErrorNumPanel, java.awt.BorderLayout.SOUTH);

        erroresPanel.add(panelLexical);

        panelSyntactic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sintácticos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        panelSyntactic.setLayout(new java.awt.BorderLayout());

        syntacticTextArea.setColumns(20);
        syntacticTextArea.setRows(5);
        errorPanelSyntactic.setViewportView(syntacticTextArea);

        panelSyntactic.add(errorPanelSyntactic, java.awt.BorderLayout.CENTER);

        syntacticErrorNumPanel.setLayout(new java.awt.BorderLayout());

        labelSyntacticErrorNum.setText("Número de Errores:");
        syntacticErrorNumPanel.add(labelSyntacticErrorNum, java.awt.BorderLayout.PAGE_START);

        panelSyntactic.add(syntacticErrorNumPanel, java.awt.BorderLayout.SOUTH);

        erroresPanel.add(panelSyntactic);

        panelSemantic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semánticos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        panelSemantic.setLayout(new java.awt.BorderLayout());

        semanticTextArea.setColumns(20);
        semanticTextArea.setRows(5);
        errorPanelSemantic.setViewportView(semanticTextArea);

        panelSemantic.add(errorPanelSemantic, java.awt.BorderLayout.CENTER);

        semanticErrorNumPanel.setLayout(new java.awt.BorderLayout());

        labelSemanticErrorNum.setText("Número de Errores:");
        semanticErrorNumPanel.add(labelSemanticErrorNum, java.awt.BorderLayout.PAGE_START);

        panelSemantic.add(semanticErrorNumPanel, java.awt.BorderLayout.SOUTH);

        erroresPanel.add(panelSemantic);

        errorPanel.add(erroresPanel, java.awt.BorderLayout.CENTER);

        labelTotalErrors.setText("Número Total de Errores:");
        totalErrors.add(labelTotalErrors);

        errorPanel.add(totalErrors, java.awt.BorderLayout.SOUTH);

        add(errorPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCompilate;
    private javax.swing.JButton bOptimize;
    private javax.swing.JComboBox<String> cbxCompilateCode;
    private javax.swing.JPanel codeOptimizedPanel;
    private javax.swing.JScrollPane codeOptimizedPanelArea;
    private javax.swing.JTextArea codeOptimizedTextArea;
    private javax.swing.JPanel codePanel;
    private javax.swing.JScrollPane codePanelArea;
    private javax.swing.JTextArea codeTextArea;
    private javax.swing.JPanel codesPanel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JScrollPane errorPanelLexical;
    private javax.swing.JScrollPane errorPanelSemantic;
    private javax.swing.JScrollPane errorPanelSyntactic;
    private javax.swing.JPanel erroresPanel;
    private javax.swing.JPanel executePanel;
    private javax.swing.JLabel labelLexicalErrorNum;
    private javax.swing.JLabel labelSemanticErrorNum;
    private javax.swing.JLabel labelSyntacticErrorNum;
    private javax.swing.JLabel labelTotalErrors;
    private javax.swing.JLabel lblCompilateCode;
    private javax.swing.JLabel lblFileSizeCodeNoOptimized;
    private javax.swing.JLabel lblFileSizeCodeOptimized;
    private javax.swing.JPanel lexicalErrorNumPanel;
    private javax.swing.JTextArea lexicalTextArea;
    private javax.swing.JPanel panelLexical;
    private javax.swing.JPanel panelSemantic;
    private javax.swing.JPanel panelSyntactic;
    private javax.swing.JPanel semanticErrorNumPanel;
    private javax.swing.JTextArea semanticTextArea;
    private javax.swing.JPanel syntacticErrorNumPanel;
    private javax.swing.JTextArea syntacticTextArea;
    private javax.swing.JPanel totalErrors;
    private javax.swing.JPanel typeCodePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the bRunLexical
     */
    public javax.swing.JButton getbCompilate() {
        return bCompilate;
    }

    /**
     * @return the codeTextArea
     */
    public javax.swing.JTextArea getCodeTextArea() {
        return codeTextArea;
    }

    /**
     * @return the labelLexicalErrorNum
     */
    public javax.swing.JLabel getLabelLexicalErrorNum() {
        return labelLexicalErrorNum;
    }

    /**
     * @return the labelSemanticErrorNum
     */
    public javax.swing.JLabel getLabelSemanticErrorNum() {
        return labelSemanticErrorNum;
    }

    /**
     * @return the labelSyntacticErrorNum
     */
    public javax.swing.JLabel getLabelSyntacticErrorNum() {
        return labelSyntacticErrorNum;
    }

    /**
     * @return the labelTotalErrors
     */
    public javax.swing.JLabel getLabelTotalErrors() {
        return labelTotalErrors;
    }

    /**
     * @return the lexicalTextArea
     */
    public javax.swing.JTextArea getLexicalTextArea() {
        return lexicalTextArea;
    }

    /**
     * @return the semanticTextArea
     */
    public javax.swing.JTextArea getSemanticTextArea() {
        return semanticTextArea;
    }

    /**
     * @return the syntacticTextArea
     */
    public javax.swing.JTextArea getSyntacticTextArea() {
        return syntacticTextArea;
    }

    /**
     * @return the bRunSemantic
     */
    public javax.swing.JButton getbRunSemantic() {
        return bCompilate;
    }

    /**
     * @return the bOptimize
     */
    public javax.swing.JButton getbOptimize() {
        return bOptimize;
    }

    /**
     * @return the cbxCompilateCode
     */
    public javax.swing.JComboBox<String> getCbxCompilateCode() {
        return cbxCompilateCode;
    }

    /**
     * @return the codeOptimizedTextArea
     */
    public javax.swing.JTextArea getCodeOptimizedTextArea() {
        return codeOptimizedTextArea;
    }

    /**
     * @return the lblFileSizeCodeNoOptimized
     */
    public javax.swing.JLabel getLblFileSizeCodeNoOptimized() {
        return lblFileSizeCodeNoOptimized;
    }

    /**
     * @return the lblFileSizeCodeOptimized
     */
    public javax.swing.JLabel getLblFileSizeCodeOptimized() {
        return lblFileSizeCodeOptimized;
    }
    
}
